project:
  type: default
  output-dir: _output
  render:
    - index.qmd

bibliography: references.bib

filters:
  - bibentry
  - reusable-footnotes

reusable-footnotes:
  enabled: true
  backlinks: true
  scope: page
  numbering: page
  docx-scope: pagebreak

format:
  html:
    toc: true
    html-math-method: katex
    include-in-header: includes/google-tag.html
  pdf:
    toc: true
    pdf-engine: lualatex
    mainfont: "DejaVu Serif"
    monofont: "DejaVu Sans Mono"
  docx:
    toc: false
    reference-doc: _extensions/reusable-footnotes/reference-page.docx
