project:
  type: default
  output-dir: _output

bibliography: references.bib

filters:
  - bibentry
  - reusable-footnotes

reusable-footnotes:
  enabled: true
  backlinks: true
  docx-scope: section

format:
  html:
    toc: true
    html-math-method: katex
  pdf:
    toc: true
    pdf-engine: lualatex
    mainfont: "DejaVu Serif"
    monofont: "DejaVu Sans Mono"
  docx:
    toc: false
