#!/usr/bin/env python3
"""Normalize repeated DOCX footnotes generated by reusable-footnotes.

Pandoc/Quarto's DOCX writer emits one Word footnote for every Note node. This
post-render pass detects footnotes with equivalent OOXML content, keeps the
first real footnote, and replaces later references with a discreet superscript
hyperlink carrying the same visible number.

Only the Python standard library is required.

Usage:
    python reusable-footnotes-docx.py file.docx [other.docx ...]

When called as a Quarto post-render hook without arguments, it reads
QUARTO_PROJECT_OUTPUT_FILES and processes each .docx listed there.
"""

from __future__ import annotations

import copy
import os
import re
import sys
import tempfile
import zipfile
from pathlib import Path
import xml.etree.ElementTree as ET

W = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
R = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
PKG_REL = "http://schemas.openxmlformats.org/package/2006/relationships"
XML = "http://www.w3.org/XML/1998/namespace"
MARKER_RE = re.compile(r"^__REUSABLE_FOOTNOTE_GROUP_(\d{6})__$")

# Keep common prefixes readable when rewritten.
for prefix, uri in {
    "w": W,
    "r": R,
    "m": "http://schemas.openxmlformats.org/officeDocument/2006/math",
    "o": "urn:schemas-microsoft-com:office:office",
    "v": "urn:schemas-microsoft-com:vml",
    "w10": "urn:schemas-microsoft-com:office:word",
    "a": "http://schemas.openxmlformats.org/drawingml/2006/main",
    "pic": "http://schemas.openxmlformats.org/drawingml/2006/picture",
    "wp": "http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing",
}.items():
    ET.register_namespace(prefix, uri)


def q(ns: str, local: str) -> str:
    return f"{{{ns}}}{local}"


def relation_targets(zip_file: zipfile.ZipFile) -> dict[str, tuple[str, str, str]]:
    name = "word/_rels/footnotes.xml.rels"
    if name not in zip_file.namelist():
        return {}
    root = ET.fromstring(zip_file.read(name))
    result: dict[str, tuple[str, str, str]] = {}
    for rel in root.findall(q(PKG_REL, "Relationship")):
        rid = rel.get("Id")
        if rid:
            result[rid] = (
                rel.get("Type", ""),
                rel.get("Target", ""),
                rel.get("TargetMode", ""),
            )
    return result


def _sort_attributes(node: ET.Element) -> None:
    for el in node.iter():
        if len(el.attrib) > 1:
            attrs = sorted(el.attrib.items())
            el.attrib.clear()
            el.attrib.update(attrs)



def extract_and_remove_group_marker(footnote: ET.Element) -> str | None:
    parents = parent_map(footnote)
    marker: str | None = None
    for text in list(footnote.iter(q(W, "t"))):
        value = text.text or ""
        match = MARKER_RE.match(value)
        if not match:
            continue
        marker = match.group(1)
        run = parents.get(text)
        if run is not None:
            parent = parents.get(run)
            if parent is not None:
                parent.remove(run)
        break
    return marker

def canonical_xml(footnote: ET.Element, rels: dict[str, tuple[str, str, str]]) -> bytes:
    node = copy.deepcopy(footnote)
    node.attrib.pop(q(W, "id"), None)

    for el in node.iter():
        # Revision-session identifiers are not semantic content.
        for attr in list(el.attrib):
            local = attr.rsplit("}", 1)[-1]
            if local.startswith("rsid"):
                del el.attrib[attr]

        rid = el.get(q(R, "id"))
        if rid and rid in rels:
            typ, target, mode = rels[rid]
            el.set(q(R, "id"), f"REL::{typ}::{target}::{mode}")

    _sort_attributes(node)
    return ET.tostring(node, encoding="utf-8", short_empty_elements=True)


def iter_real_footnotes(root: ET.Element):
    for fn in root.findall(q(W, "footnote")):
        if fn.get(q(W, "type")):
            continue
        fid = fn.get(q(W, "id"))
        if fid is None or fid in {"-1", "0"}:
            continue
        yield fn


def parent_map(root: ET.Element) -> dict[ET.Element, ET.Element]:
    return {child: parent for parent in root.iter() for child in parent}


def replace_reference_with_link(
    ref: ET.Element,
    parents: dict[ET.Element, ET.Element],
    bookmark_name: str,
    display_number: int,
) -> None:
    run = parents.get(ref)
    if run is None:
        return
    parent = parents.get(run)
    if parent is None:
        return
    children = list(parent)
    index = children.index(run)

    hyperlink = ET.Element(q(W, "hyperlink"))
    hyperlink.set(q(W, "anchor"), bookmark_name)
    hyperlink.set(q(W, "history"), "1")

    new_run = ET.SubElement(hyperlink, q(W, "r"))
    rpr = ET.SubElement(new_run, q(W, "rPr"))
    style = ET.SubElement(rpr, q(W, "rStyle"))
    style.set(q(W, "val"), "FootnoteReference")
    text = ET.SubElement(new_run, q(W, "t"))
    text.text = str(display_number)

    parent.remove(run)
    parent.insert(index, hyperlink)


def add_bookmark_to_footnote(
    footnote: ET.Element,
    bookmark_name: str,
    bookmark_id: int,
) -> None:
    paragraph = footnote.find(q(W, "p"))
    if paragraph is None:
        paragraph = ET.SubElement(footnote, q(W, "p"))

    start = ET.Element(q(W, "bookmarkStart"))
    start.set(q(W, "id"), str(bookmark_id))
    start.set(q(W, "name"), bookmark_name)
    end = ET.Element(q(W, "bookmarkEnd"))
    end.set(q(W, "id"), str(bookmark_id))

    paragraph.insert(0, start)
    paragraph.append(end)


def process_docx(path: Path) -> tuple[int, int]:
    if not path.exists() or path.suffix.lower() != ".docx":
        return (0, 0)

    with zipfile.ZipFile(path, "r") as zin:
        names = set(zin.namelist())
        if "word/document.xml" not in names or "word/footnotes.xml" not in names:
            return (0, 0)

        document_root = ET.fromstring(zin.read("word/document.xml"))
        footnotes_root = ET.fromstring(zin.read("word/footnotes.xml"))
        rels = relation_targets(zin)

        canonical_for_id: dict[str, str] = {}
        first_by_key: dict[bytes, str] = {}
        footnote_by_id: dict[str, ET.Element] = {}

        for fn in iter_real_footnotes(footnotes_root):
            fid = fn.get(q(W, "id"))
            assert fid is not None
            footnote_by_id[fid] = fn

            marker = extract_and_remove_group_marker(fn)
            if marker is not None:
                key = f"MARKER::{marker}".encode("ascii")
            else:
                key = canonical_xml(fn, rels)

            first = first_by_key.setdefault(key, fid)
            canonical_for_id[fid] = first

        duplicate_ids = {
            fid: canonical
            for fid, canonical in canonical_for_id.items()
            if fid != canonical
        }
        if not duplicate_ids:
            return (0, len(footnote_by_id))

        # Number canonical notes in body-reference order after deduplication.
        display_number: dict[str, int] = {}
        next_number = 0
        refs = list(document_root.iter(q(W, "footnoteReference")))
        for ref in refs:
            fid = ref.get(q(W, "id"))
            if fid is None:
                continue
            canonical = canonical_for_id.get(fid, fid)
            if canonical not in display_number:
                next_number += 1
                display_number[canonical] = next_number

        existing_bookmark_ids: list[int] = []
        for root in (document_root, footnotes_root):
            for mark in root.iter(q(W, "bookmarkStart")):
                raw = mark.get(q(W, "id"))
                try:
                    existing_bookmark_ids.append(int(raw))
                except (TypeError, ValueError):
                    pass
        next_bookmark_id = max(existing_bookmark_ids + [900000]) + 1

        bookmark_for_canonical: dict[str, str] = {}
        canonicals_with_duplicates = sorted(
            set(duplicate_ids.values()),
            key=lambda x: display_number.get(x, 10**9),
        )
        for canonical in canonicals_with_duplicates:
            number = display_number.get(canonical)
            if number is None or canonical not in footnote_by_id:
                continue
            name = f"rfn_note_{number}"
            bookmark_for_canonical[canonical] = name
            add_bookmark_to_footnote(
                footnote_by_id[canonical], name, next_bookmark_id
            )
            next_bookmark_id += 1

        replacements = 0
        parents = parent_map(document_root)
        for ref in refs:
            fid = ref.get(q(W, "id"))
            if fid not in duplicate_ids:
                continue
            canonical = duplicate_ids[fid]
            number = display_number.get(canonical)
            bookmark = bookmark_for_canonical.get(canonical)
            if number is None or bookmark is None:
                continue
            replace_reference_with_link(ref, parents, bookmark, number)
            replacements += 1

        for fn in list(iter_real_footnotes(footnotes_root)):
            fid = fn.get(q(W, "id"))
            if fid in duplicate_ids:
                footnotes_root.remove(fn)

        document_xml = ET.tostring(
            document_root, encoding="utf-8", xml_declaration=True
        )
        footnotes_xml = ET.tostring(
            footnotes_root, encoding="utf-8", xml_declaration=True
        )

        fd, temp_name = tempfile.mkstemp(suffix=".docx", dir=str(path.parent))
        os.close(fd)
        temp_path = Path(temp_name)
        try:
            with zipfile.ZipFile(temp_path, "w", zipfile.ZIP_DEFLATED) as zout:
                for item in zin.infolist():
                    if item.filename == "word/document.xml":
                        data = document_xml
                    elif item.filename == "word/footnotes.xml":
                        data = footnotes_xml
                    else:
                        data = zin.read(item.filename)
                    zout.writestr(item, data)
        except Exception:
            temp_path.unlink(missing_ok=True)
            raise

    os.replace(temp_path, path)
    return (replacements, len(footnote_by_id) - len(duplicate_ids))


def paths_from_environment() -> list[Path]:
    raw = os.getenv("QUARTO_PROJECT_OUTPUT_FILES", "")
    if not raw:
        return []
    return [
        Path(line.strip())
        for line in raw.splitlines()
        if line.strip().lower().endswith(".docx")
    ]


def main(argv: list[str]) -> int:
    paths = [Path(arg) for arg in argv[1:]] if len(argv) > 1 else paths_from_environment()
    if not paths:
        return 0

    for path in paths:
        replacements, unique = process_docx(path)
        if replacements:
            print(
                f"reusable-footnotes: {path} — {replacements} recorrência(s) "
                f"remetida(s) a {unique} nota(s) única(s)."
            )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
